name: Java CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest
	
    steps:
      - uses: actions/checkout@v4

      - name: Test Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Test
        run: ./mvnw test

      - name: Build Jar
        run: ./mvnw package -DskipTests

      - name: Build Docker Image
        run: docker build -f Dockerfile.ecs -t todolistplus .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: todolistplus_back
        run: |
          docker tag todolistplus:latest \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest