name: Java CI

on:
  push:
    branches:
      - master
    paths:
      - src/**

  pull_request:
    branches:
      - master
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample_schema
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - uses: actions/checkout@v4

      - name: Test Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Test
        run: ./mvnw test
